### ISSUE TITLE
Game crashes out of nowhere

### ISSUE THREAD

**Issue by Flow34** [EverestAPI/Everest#31]
Whenever I try playing GhostNet with my friend, the game just crashes. However, on steam, it says that the game is still running. This is the log:

Ver 1.2.5.3 [Everest: 772-azure-0fa40]
01/10/2019 17:45:17
System.InvalidOperationException: A previous Draw call threw an unhandled exception. See InnerException for details. ---> System.OutOfMemoryException: Memória insuficiente para continuar a execução do programa.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(tagRECT* pSource, tagRECT* pDest, HWND__* hOverride)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.EndDraw()
   at Microsoft.Xna.Framework.Game.EndDraw()
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Paint(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameWindow.OnPaint()
   at Microsoft.Xna.Framework.WindowsGameWindow.mainForm_Paint(Object sender, PaintEventArgs e)
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Monocle.Engine.RunWithLogging() in D:\a\1\s\Celeste.Mod.mm\Patches\Monocle\Engine.cs:line 29

**Comment by leo60228** [comment]
Custom maps can use more memory than the original game did, causing this crash. Everest contains a feature to work around this, but locations with lots of textures (such as the final Badeline fight) may slow down. Open ModSettings/Everest.yaml in a text editor (f.e. Notepad) and change `LazyLoading` from `false` to `true` to enable this.

(FYI, this question and a few others are answered [on the wiki](https://github.com/EverestAPI/Resources/wiki))

**Comment by leo60228** [comment]
@0x0ade There hasn't been an update in nearly a month, can you please close this?
