### ISSUE TITLE
Game Crashing when Mapping

### ISSUE THREAD

**Issue by RedBoule1** [EverestAPI/Everest#356]
So when mapping with Ahorn via Olympus, when i save my map, my game crashes when i click on the celeste icon again. The thing is, it doesn't happen all the time. Sometimes i can save a lot of times before crashing and sometimes it crashes almost all the time.
I'm pretty sure it started happening this week and i don't know what i did to trigger the crashes.

Here is the error log:
[error_log.txt](https://github.com/EverestAPI/Everest/files/6947533/error_log.txt)

**Comment by coloursofnoise** [comment]
Relevant portion of the error log:
```
Ver 1.4.0.0-xna [Everest: 2961-azure-a2876]
08/06/2021 15:32:26
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Monocle.VirtualContent.UnloadOverworld() in D:\a\1\s\Celeste.Mod.mm\Patches\Monocle\VirtualContent.cs:line 76
   at Celeste.LevelLoader.<>c.<ctor>b__3_0() in D:\a\1\s\Celeste.Mod.mm\Patches\LevelLoader.cs:line 38
```
Locking the `VirtualContent.assets` list before iterating it would hopefully be enough to mitigate this
