### ISSUE TITLE
Fix/rework --headless mode

### ISSUE THREAD

**Issue by coloursofnoise** [EverestAPI/Everest#381]
The `EVEREST_HEADLESS` mode broke at some point, which was previously intended to be used for testing or as a server (GhostNet)

Currently crashes with the following errors:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at Monocle.Engine.RunWithLogging() in D:\a\1\s\Celeste.Mod.mm\Patches\Monocle\Engine.cs:line 34

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Game.Dispose()
   at Celeste.Celeste.orig_Main(String[] args)
   at Celeste.Celeste.MainInner(String[] args) in D:\a\1\s\Celeste.Mod.mm\Patches\Celeste.cs:line 161
```

**Comment by Wartori54** [comment]
As of #855 (and #896) headless mode was rewritten and it is currently working.
[This](https://github.com/EverestAPI/Resources/wiki/Command-Line-Arguments#miniinstaller) covers how it can be enabled now.
