### ISSUE TITLE
Debug RC teleport endpoint fails for B and C sides.

### ISSUE THREAD

**Issue by wishcresp** [EverestAPI/Everest#437]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

GET requests to the debug rc teleport endpoint for B sides and C sides fail unless the exact level is already loaded. Responses return a 200 OK code anyway even when the teleport fails.

eg. Try teleporting to a C side from the main menu: http://localhost:32270/tp?area=Celeste/1-ForsakenCity&side=C&level=01

The teleport will only succeed if the teleport destination is currently loaded. The issue does not affect the A-sides.

### Steps to reproduce

1. Load the game with Everest installed.
2. While on the main menu, perform a get request to teleport to any vanilla C side room. eg. http://localhost:32270/tp?area=Celeste/1-ForsakenCity&side=C&level=01

### Expected behavior

Madeline should teleport to the C side.

### Operating System

Windows 10

### Everest Version

3282, 3322

### Additional context

(04/17/2022 15:43:42) [Everest] [Verbose] [debugrc] Requested: /tp?area=Celeste/1-ForsakenCity&side=C&level=01
(04/17/2022 15:43:42) [Everest] [Info] [LevelLoader] Loading level Celeste/1-ForsakenCity
(04/17/2022 15:43:42) [Everest] [Warn] [LoadLevel] Failed loading level 1
--------------------------------
Detailed exception log:
--------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at Celeste.Level.orig_LoadLevel(IntroTypes playerIntro, Boolean isFromLoader)
   at Celeste.Level.LoadLevel(IntroTypes playerIntro, Boolean isFromLoader) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Level.cs:line 187
(04/17/2022 15:43:59) [Everest] [Info] [LevelLoader] Loading level Celeste/1-ForsakenCity
(04/17/2022 15:44:02) [Everest] [Verbose] [debugrc] Requested: /tp?area=Celeste/1-ForsakenCity&side=C&level=01
(04/17/2022 15:44:02) [Everest] [Info] [LevelLoader] Loading level Celeste/1-ForsakenCity
(04/17/2022 15:44:02) [Everest] [Warn] [LoadLevel] Failed loading level 1

**Comment by wishcresp** [comment]
Possible side effect of the same issue. Teleporting to http://localhost:32270/tp?area=Celeste/6-Reflection&side=C&level=02 will bring you to room 02 in 6A instead of throwing the null reference exception. If 6C is currently loaded, it will teleport you to the correct screen of 6C instead. I haven't tried the other A sides. Behavior might be related to the same debug id existing in both sides?
