### ISSUE TITLE
Game crashed when a zipped mod trying to load native library

### ISSUE THREAD

**Issue by NoMathExpectation** [EverestAPI/Everest#761]
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

I am developing a mod and I need to use some native library.
I implemented this by extracting libraries to mod cache and referencing using `DllImport`. [code](https://github.com/NoMathExpectation/Celestibility/blob/b4fd0a3e482f79b7aa5ae2cd7de7f3d0dc4feb93/Source/Speech/ZDSRSpeechProvider.cs#L31)
The library loading works fine when running the mod in an **unzipped** form.
But when I **zip** the mod and run, the native library loading will fail and the game will crash:
```
Ver 1.4.0.0-fna [Everest: 4739-azure-62e69]
04/26/2024 19:22:13
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Celeste.Mod.EverestModuleAssemblyContext.LoadUnmanagedFromThisMod(String name) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs:line 516
   at Celeste.Mod.EverestModuleAssemblyContext.LoadUnmanagedLocal(String name) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs:line 372
   at Celeste.Mod.EverestModuleAssemblyContext.LoadUnmanagedDll(String name) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs:line 309
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at NoMathExpectation.Celeste.Celestibility.Speech.ZDSRSpeechProvider.InitTTS(Int32 type, String channelName, Boolean bKeyDownInterrupt)
   at NoMathExpectation.Celeste.Celestibility.Speech.ZDSRSpeechProvider..ctor()
   at NoMathExpectation.Celeste.Celestibility.Speech.SpeechEngine.Init()
   at NoMathExpectation.Celeste.Celestibility.CelestibilityModule.Load()
   at Celeste.Mod.Everest.Register(EverestModule module)
   at Celeste.Mod.Everest.Loader.LoadModAssembly(EverestModuleMetadata meta, Assembly asm)
   at Celeste.Mod.Everest.Loader.LoadMod(EverestModuleMetadata meta)
   at Celeste.Mod.Everest.Loader.LoadModDelayed(EverestModuleMetadata meta, Action callback)
   at Celeste.Mod.Everest.Loader.LoadZip(String archive)
   at Celeste.Mod.Everest.Loader.LoadAuto()
   at Celeste.Mod.Everest.Boot()
   at Celeste.Celeste..ctor()
   at Celeste.Celeste.orig_Main(String[] args)

```

### Steps to reproduce

1. Go to the mod [repository](https://github.com/NoMathExpectation/Celestibility), compile the source code and pack to a zip.
2. Put the **zipped** mod to the mod folder and run the game.

### Expected behavior

The mod will load correctly just like in unzipped form.

### Operating System

Windows 11

### Everest Version

4739

### Additional context

[errorLog.txt](https://github.com/EverestAPI/Everest/files/15130336/errorLog.txt)
[log.txt](https://github.com/EverestAPI/Everest/files/15130338/log.txt)

**Comment by psyGamer** [comment]
> `private const string dll = "Mods/Cache/Celestibility/nativebin/ZDSRAPI_x64";`

99% sure thats your issue. The DLL name should just be the the name, not the full path.
You can look at [ImGuiHelper](https://github.com/swoolcock/ImGuiHelper) or [TASRecorder](https://github.com/psyGamer/TASRecorder) on how to properly use native libraries.
Theses are the paths, file names you'll need (with the root being the directory of your mod DLL): https://github.com/EverestAPI/Everest/blob/c73506517a2d03f7fded2c34bf1c7e37fef727f3/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs#L34-L39 and https://github.com/EverestAPI/Everest/blob/c73506517a2d03f7fded2c34bf1c7e37fef727f3/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs#L510-L515

**Comment by NoMathExpectation** [comment]
I have changed and committed the code according to your suggestion, but the game still crashes and throws the same exception.
Code: https://github.com/NoMathExpectation/Celestibility/blob/75969d0e4c7c49f4e3c6e82ce2373fd0c63b4341/Source/Speech/ZDSRSpeechProvider.cs#L45
```
Ver 1.4.0.0-fna [Everest: 4739-azure-62e69]
04/26/2024 21:53:36
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Celeste.Mod.EverestModuleAssemblyContext.LoadUnmanagedFromThisMod(String name) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs:line 516
   at Celeste.Mod.EverestModuleAssemblyContext.LoadUnmanagedLocal(String name) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs:line 372
   at Celeste.Mod.EverestModuleAssemblyContext.LoadUnmanagedDll(String name) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs:line 309
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at NoMathExpectation.Celeste.Celestibility.Speech.ZDSRSpeechProvider.InitTTS(Int32 type, String channelName, Boolean bKeyDownInterrupt)
   at NoMathExpectation.Celeste.Celestibility.Speech.ZDSRSpeechProvider..ctor()
   at NoMathExpectation.Celeste.Celestibility.Speech.SpeechEngine.Init()
   at NoMathExpectation.Celeste.Celestibility.CelestibilityModule.Load()
   at Celeste.Mod.Everest.Register(EverestModule module)
   at Celeste.Mod.Everest.Loader.LoadModAssembly(EverestModuleMetadata meta, Assembly asm)
   at Celeste.Mod.Everest.Loader.LoadMod(EverestModuleMetadata meta)
   at Celeste.Mod.Everest.Loader.LoadModDelayed(EverestModuleMetadata meta, Action callback)
   at Celeste.Mod.Everest.Loader.LoadZip(String archive)
   at Celeste.Mod.Everest.Loader.LoadAuto()
   at Celeste.Mod.Everest.Boot()
   at Celeste.Celeste..ctor()
   at Celeste.Celeste.orig_Main(String[] args)

```

**Comment by SnipUndercover** [comment]
This seems to be the cause of the crash. The mod's `Hash`es are `null` and as such the LINQ query crashes.
https://github.com/EverestAPI/Everest/blob/c73506517a2d03f7fded2c34bf1c7e37fef727f3/Celeste.Mod.mm/Mod/Module/EverestModuleAssemblyContext.cs#L523

The stacktrace tells most of the story. Here's a section of `Everest.Loader.LoadMod()`:
https://github.com/EverestAPI/Everest/blob/c73506517a2d03f7fded2c34bf1c7e37fef727f3/Celeste.Mod.mm/Mod/Everest/Everest.Loader.cs#L491-L507

`Hash`es are calculated in `EverestModuleMetadata.RegisterMod()`:
https://github.com/EverestAPI/Everest/blob/c73506517a2d03f7fded2c34bf1c7e37fef727f3/Celeste.Mod.mm/Mod/Module/EverestModuleMetadata.cs#L127-L137

- `Everest.Loader.LoadModAssembly()` is called, which invokes `Everest.Register(EverestModule)`, which then calls `EverestModule.Load()`.
- Skipping ahead, `ZDSRSpeechProvider.InitTTS(int, string, bool)` is P/Invoked, which triggers the unmanaged DLL resolution.
- Skipping further ahead, `EverestModuleAssemblyContext.LoadUnmanagedFromThisMod(string)` is called, which tries to retrieve the mod's `Hash`.
- Because `EverestModuleMetadata.RegisterMod()` has not been called yet, the mod's `Hash` is `null` and the game crashes.
