### ISSUE TITLE
FMOD live update crash when restarting after Everest update

### ISSUE THREAD

**Issue by Kalobi** [EverestAPI/Everest#810]
When restarting the game after an in-game Everest update with FMOD Live Update enabled, FMOD crashes with `ERR_NOTREADY`. Sample crash log:
```
Ver 1.4.0.0-fna [Everest: 4886-azure-e5327]
07/10/2024 23:52:11
System.Exception: FMOD Failed: ERR_NOTREADY (Operation could not be performed because specified sound/DSP connection is not ready.)
   at Celeste.Audio.CheckFmod(RESULT result) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 42
   at Celeste.AudioExt.CheckFMOD(RESULT result) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 392
   at Celeste.Audio.Banks.Load(String name, Boolean loadStrings) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 337
   at DMD<System.Void Celeste.Audio:Init()>()
   at Celeste.Mod.SpeedrunTool.Other.MuteInBackground.AudioOnInit(orig_Init orig)
   at Hook<System.Void Celeste.Mod.SpeedrunTool.Other.MuteInBackground::AudioOnInit(On.Celeste.Audio+orig_Init)>()
   at SyncProxy<System.Void Celeste.Audio:Init()>()
   at DMD<System.Void Celeste.GameLoader:LoadThread()>(GameLoader this)
   at SkinModHelper.Module.SkinModHelperModule.GameLoaderLoadThreadHook(orig_LoadThread orig, GameLoader self)
   at Hook<System.Void SkinModHelper.Module.SkinModHelperModule::GameLoaderLoadThreadHook(On.Celeste.GameLoader+orig_LoadThread,Celeste.GameLoader)>(GameLoader )
   at Hook<System.Void Celeste.Mod.SkinModHelper.LoaderHook::GameLoaderLoadThreadHook(On.Celeste.GameLoader+orig_LoadThread,Celeste.GameLoader)>(GameLoader )
   at SyncProxy<System.Void Celeste.GameLoader:LoadThread()>(GameLoader )
   at Celeste.RunThread.RunThreadWithLogging(Action method)
```

**Comment by tryobytee** [comment]
Experiencing this issue with latest everest v5288

```
Ver 1.4.0.0-fna [Everest: 5288-azure-164d4]
01/26/2025 17:05:07
System.Exception: FMOD Failed: ERR_NOTREADY (Operation could not be performed because specified sound/DSP connection is not ready.)
   at Celeste.Audio.CheckFmod(RESULT result) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 42
   at Celeste.AudioExt.CheckFMOD(RESULT result) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 392
   at Celeste.Audio.Banks.Load(String name, Boolean loadStrings) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 337
   at DMD<System.Void Celeste.Audio:Init()>()
   at Celeste.Mod.SpeedrunTool.Other.MuteInBackground.AudioOnInit(orig_Init orig)
   at Hook<System.Void Celeste.Mod.SpeedrunTool.Other.MuteInBackground::AudioOnInit(On.Celeste.Audio+orig_Init)>()
   at SyncProxy<System.Void Celeste.Audio:Init()>()
   at Celeste.GameLoader.LoadThread()
   at Celeste.RunThread.RunThreadWithLogging(Action method)
```

this seems to happen on startup when loading contorthelper consistently, reverting to 5285 stable seemed to fix it, I've gotten this crash sporadically in the past but this is the only time it's been consistent

also the game didn't open errorLog.txt in this case which it has done in the past when this crash happened.
