### ISSUE TITLE
Can't update Everest

### ISSUE THREAD

**Issue by creator1creeper1** [EverestAPI/Everest#831]
### My mods and Everest install are up to date

No

### I have recreated the bug with only Everest OR a minimum number of mods enabled

No

### Describe the bug

I can't update Everest to the current version.

```
Detailed exception log:
--------------------------------
System.ComponentModel.Win32Exception: Das System kann die angegebene Datei nicht finden
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Celeste.Mod.Everest.Updater._UpdateStart(OuiLoggedProgress progress, Entry version) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Everest/Everest.Updater.cs:line 0
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 143 in IL for OuiFileSelectSlot.orig_Render, for custom cassettes (1/2).
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 163 in IL for OuiFileSelectSlot.orig_Render, for custom cassettes (2/2).
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 248 in IL for OuiFileSelectSlot.orig_Render, for custom hearts.
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 143 in IL for OuiFileSelectSlot.orig_Render, for custom cassettes (1/2).
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 163 in IL for OuiFileSelectSlot.orig_Render, for custom cassettes (2/2).
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 248 in IL for OuiFileSelectSlot.orig_Render, for custom hearts.
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 143 in IL for OuiFileSelectSlot.orig_Render, for custom cassettes (1/2).
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 163 in IL for OuiFileSelectSlot.orig_Render, for custom cassettes (2/2).
(10/19/2024 23:12:34) [Everest] [Info] [AltSidesHelper] Modding file select slot at 248 in IL for OuiFileSelectSlot.orig_Render, for custom hearts.
```

### Steps to reproduce

Click on "Update Everest to 5052"

### Expected behavior

The update should work.

### Operating System

Windows 10

### Everest Version

3761-azure-491f9

### Additional context

[log.txt](https://github.com/user-attachments/files/17447380/log.txt)

**Comment by SnipUndercover** [comment]
Please use Olympus to update from such an old Everest version, instead of the in-game updater.
![Olympus with cog in the upper right circled in red](https://maddie480.ovh/img/olympus-everest-update.png)
