### ISSUE TITLE
Everest build 1339: Levelset with 0 strawberries causes ArgumentOutOfRange in get_MaxStrawberries

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/Everest#87]
```
Celeste Error Log
==========================================

Ver 1.3.1.2 [Everest: 1339-azure-0f7ea]
01/12/2020 21:57:44
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Celeste.LevelSetStats.get_MaxStrawberries() in d:\a\1\s\Celeste.Mod.mm\Patches\SaveData.cs:line 494
   at Celeste.OuiFileSelectSlot..ctor(Int32 index, OuiFileSelect fileSelect, SaveData data) in d:\a\1\s\Celeste.Mod.mm\Patches\OuiFileSelectSlot.cs:line 38
   at Celeste.OuiFileSelect.LoadThread()
   at Celeste.RunThread.RunThreadWithLogging(Action method)
```

Note to self: map is in `Celeste\Mods\Name\Maps\Problem.bin` and is the only map in the levelset

**Comment by GreyMario** [comment]
***Update:*** This was caused by the map file being in `Celeste\Mods\Name\Maps\Problem.bin` instead of in a dedicated campaign folder. I'll go ahead and call this _low priority_ to fix, but I think we want to still look into it pretty soon.

**Comment by GreyMario** [comment]
NOPE, scratch that. It's still crashing.

**Comment by GreyMario** [comment]
Ah, since this is an issue introduced in Subchapters, I'll just leave this one under Ade's control.

**Comment by 0x0ade** [comment]
I'd like to get a copy of the .bin in question, as I'm unable to replicate it locally with the given info.
